{% set name = "pytest" %}
{% set version = "9.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 75186651a92bd89611d1d9fc20f0b4345fd827c41ccd5c299a868a05d70edf11

build:
  skip: true  # [py<310]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pytest=pytest:console_main
    - py.test=pytest:console_main

requirements:
  host:
    - pip
    - python
    - setuptools >=77
    - setuptools-scm >=6.2.3
    - toml
  run:
    - python
    - iniconfig >=1.0.1
    - packaging >=22
    - pluggy >=1.5,<2
    - colorama >=0.4  # [win]
    - exceptiongroup >=1  # [py<311]
    - tomli >=1  # [py<311]
    - pygments >=2.7.2
  run_constrained:
    # pytest-faulthandler 2 is a dummy package.
    # if an older version of fault-handler is installed, it will conflict with pytest >=5.
    - pytest-faulthandler >=2
    - attrs >=19.2
    - hypothesis >=3.56

test:
  downstreams:
    # - allure-pytest
    # - allure-pytest-bdd
    # - inline-snapshot
    # - pytest-flake8
    # - pytest-selenium
    # - pytest-subtests
    # - pytest-sugar
    # - pytest-xdist

    - medspacy_quickumls
    - nbsmoke
    - pytest-arraydiff
    - pytest-astropy
    - pytest-astropy-header
    - pytest-asyncio
    - pytest-azurepipelines
    - pytest-base-url
    - pytest-bdd
    - pytest-benchmark
    - pytest-cache
    - pytest-codspeed
    - pytest-console-scripts
    - pytest-cov
    - pytest-csv
    - pytest-dependency
    - pytest-docker-tools
    - pytest-doctestplus
    - pytest-filter-subpackage
    - pytest-flakefinder
    - pytest-forked
    - pytest-grpc
    - pytest-html
    - pytest-json
    - pytest-jupyter
    - pytest-localserver
    - pytest-metadata
    - pytest-mock
    - pytest-mpi
    - pytest-nunit
    - pytest-ordering
    - pytest-pep8
    - pytest-pretty
    - pytest-qt
    - pytest-randomly
    - pytest-remotedata
    - pytest-replay
    - pytest-rerunfailures
    - pytest-shard
    - pytest-socket
    - pytest-subprocess
    - pytest-timeout
    - pytest-tornado
    - pytest-tornasync
    - pytest-trio
    - pytest-variables
    - pytest-xprocess
  source_files:
    - testing
    - src
  imports:
    - pytest
    - _pytest
    - _pytest._code
    - _pytest._io
    - _pytest._py
    - _pytest.assertion
    - _pytest.config
    - _pytest.mark
  requires:
    - pip
    - pytest
  commands:
    - pytest -h
    - pip check
    - python -c "from importlib.metadata import version; assert(version('{{ name }}')=='{{ version }}')"
    - pytest testing -v --markers --fixtures --ignore=testing/example_scripts

about:
  home: https://docs.pytest.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org
  dev_url: https://github.com/pytest-dev/pytest

extra:
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
