{% set name = "pytest" %}
{% set version = "6.2.3" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 671238a46e4df0f3498d1c3270e5deb9b32d25134c99b7d75370a68cfbe9b634

build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python

about:
  home: The package home page
  license: MIT
  license_family: MIT
  license_file: 
  summary: "pytest: simple powerful testing with Python"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - your-github-id-here
