{% set version = "7.1.1" %}

package:
  name: pytest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest/pytest-{{ version }}.tar.gz
  sha256: 841132caef6b1ad17a9afde46dc4f6cfa59a05f9555aae5151f73bdf2820ca63

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - py.test = py.test:console_main
    - pytest = py.test:console_main

requirements:
  host:
    - pip
    - python
    - setuptools >=42.0
    - setuptools_scm >=6.2.3
    - wheel
    - toml
  run:
    - python
    - attrs >=19.2.0
    - iniconfig
    - packaging
    - pluggy >=0.12,<2.0
    - py >=1.8.2
    - tomli >=1.0.0
    - atomicwrites >=1.0  # [win]
    - colorama  # [win]
    - importlib-metadata >=0.12  # [py<38]
  run_constrained:
    # pytest-faulthandler 2 is a dummy package.
    # if an older version of fault-handler is installed, it will conflict with pytest >=5.
    - pytest-faulthandler >=2

test:
  commands:
    - pytest -h
    - pip check
  imports:
    - pytest
  requires:
    - pip
  # 2022/4/4: Make additional downstream testings for the major version bump of pytest to v7.1.1
  downstreams:
    - astropy
    - jupyter_core
    - pandas

about:
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
