{% set name = "pytest" %}
{% set version = "8.3.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 70b98107bd648308a7952b06e6ca9a50bc660be218d53c257cc1fc94fda10181

build:
  skip: true  # [py<38]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pytest=pytest:console_main
    - py.test=pytest:console_main

requirements:
  host:
    - pip
    - python
    - setuptools >=61
    - wheel
    - setuptools-scm >=6.2.3
  run:
    - python
    - iniconfig
    - packaging
    - pluggy <2,>=1.5
    - colorama # [win]
    - exceptiongroup >=1.0.0 # [py<311]
    - tomli>=1 # [py<311]
  run_constrained:
    # pytest-faulthandler 2 is a dummy package.
    # if an older version of fault-handler is installed, it will conflict with pytest >=5.
    - pytest-faulthandler >=2

test:
  source_files:
    - testing
    - src
  imports:
    - pytest
    - _pytest
    - _pytest._code
    - _pytest._io
    - _pytest._py
    - _pytest.assertion
    - _pytest.config
    - _pytest.mark
  requires:
    - pip
    - pytest
  commands:
    - pytest -h
    - pip check
    - pytest testing -v --markers --fixtures --ignore=testing/example_scripts

about:
  home: https://docs.pytest.org
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
