{% set name = "pytest" %}
{% set version = "7.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pytest-{{ version }}.tar.gz
  sha256: 434afafd78b1d78ed0addf160ad2b77a30d35d4bdf8af234fe621919d9ed15e3

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation
  entry_points:
    - pytest=pytest:console_main
    - py.test=pytest:console_main

requirements:
  host:
    - pip
    - python
    - setuptools >=45.0
    - setuptools_scm >=6.2.3
    - wheel
    - toml
  run:
    - python
    - attrs >=19.2.0
    - iniconfig
    - packaging
    - pluggy >=0.12,<2.0
    - py >=1.8.2
    - tomli >=1.0.0
    - atomicwrites >=1.0  # [win]
    - colorama  # [win]
    - importlib-metadata >=0.12  # [py<38]
    - exceptiongroup
  run_constrained:
    # pytest-faulthandler 2 is a dummy package.
    # if an older version of fault-handler is installed, it will conflict with pytest >=5.
    - pytest-faulthandler >=2

test:
  imports:
    - pytest
  requires:
    - pip
  commands:
    - pytest -h
    - pip check

about:
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  skip-lints:
    # Without `packaging`, pytest errors out with:
    #   pytest <version> requires packaging, which is not installed.
    - python_build_tool_in_run
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
