{% set version = "3.0.2" %}

package:
  name: pytest
  version: {{ version }}

source:
  fn: pytest-{{ version }}.tar.gz
  url: https://github.com/pytest-dev/pytest/archive/{{ version }}.tar.gz
  sha256: 1badf28fdca28c55a2e866145a36d879166dedfa035319dc69bb71fda1dd6328

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - py.test = py.test:main

requirements:
  build:
    - python
    - py
    - setuptools
    - argparse  # [py26]
    - colorama  # [win]
  run:
    - python
    - setuptools
    - py >=1.4.29
    - argparse  # [py26]
    - colorama  # [win]

test:
  commands:
    - py.test -h
  imports:
    - pytest

about:
  home: http://pytest.org/
  license: MIT
  license_file: LICENSE
  summary: 'Simple and powerful testing with Python.'
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: http://pytest.org/latest/contents.html
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
