{% set version = "6.2.3" %}

package:
  name: pytest
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/p/pytest/pytest-{{ version }}.tar.gz
  sha256: 671238a46e4df0f3498d1c3270e5deb9b32d25134c99b7d75370a68cfbe9b634

build:
  skip: true  # [py<36]
  number: 3
  script: {{ PYTHON }} setup.py install --single-version-externally-managed --record record.txt
  entry_points:
    - py.test = py.test:console_main
    - pytest = py.test:console_main

requirements:
  build:
    - python                                 # [build_platform != target_platform]
  host:
    - pip
    - python
    - setuptools >=40.0
    - setuptools_scm
  run:
    - python
    - attrs >=19.2.0
    - iniconfig
    - more-itertools >=4.0.0
    - packaging
    - pluggy >=0.12,<1.0.0a1
    - py >=1.8.2
    - toml
    - atomicwrites >=1.0  # [win]
    - colorama  # [win]
    - importlib-metadata >=0.12  # [py<38]
  run_constrained:
    # pytest-faulthandler 2 is a dummy package.
    # if an older version of fault-handler is installed, it will conflict with pytest >=5.
    - pytest-faulthandler >=2

test:
  commands:
    - pytest -h
  imports:
    - pytest

about:
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
