{% set name = "pytest" %}
{% set version = "7.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b4bf8c45bd59934ed84001ad51e11b4ee40d40a1229d2c79f9c592b0a3f6bd8a

build:
  skip: true  # [py<37]
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  entry_points:
    - pytest=pytest:console_main
    - py.test=pytest:console_main

requirements:
  host:
    - pip
    - python
    - setuptools
    - setuptools_scm >=6.0
    - wheel
  run:
    - python
    - iniconfig
    - packaging
    - pluggy >=0.12,<2.0
    - colorama  # [win]
    - exceptiongroup  >=1.0.0  # [py<311]
    - importlib-metadata >=0.12  # [py<38]
    - tomli >=1.0.0 # [py<311]
  run_constrained:
    # pytest-faulthandler 2 is a dummy package.
    # if an older version of fault-handler is installed, it will conflict with pytest >=5.
    - pytest-faulthandler >=2

test:
  imports:
    - pytest
  requires:
    - pip
    # For full testing:
    #- argcomplete
    #- attrs >=19.2.0
    #- hypothesis >=3.56
    #- mock
    #- nose
    #- pygments >2.7.2
    #- requests
    #- setuptools
    #- xmlschema
  commands:
    - pytest -h
    - pip check

about:
  home: https://docs.pytest.org/en/latest/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Simple and powerful testing with Python.
  description: |
    The pytest framework makes it easy to write small tests, yet scales to
    support complex functional testing for applications and libraries.
  doc_url: https://docs.pytest.org/en/latest/
  dev_url: https://github.com/pytest-dev/pytest/

extra:
  skip-lints:
    # Without `packaging`, pytest errors out with:
    #   pytest <version> requires packaging, which is not installed.
    - python_build_tool_in_run
  recipe-maintainers:
    - flub
    - goanpeca
    - nicoddemus
    - ocefpaf
    - mingwandroid
