travis:
  secure:
    BINSTAR_TOKEN: jw6U44/QEsPbCGoexiOlwxvsXO5mUu9nQOKdVKPOnZMSaO+LWQccI35F474TdYWDwaSAMu7kRk1cdQILPtNJHRR6V136FTsR8cP1gnqAEWJ9TyoHzyeIJWf50ugY6EXDPunuSMGGagi975F1B6+j7V7Cb5iOqBtDVGk507cwUFJx+zDa8HLvQrrGRb2l/BCRQ+FHE5W6CdvaszIpMpq79rBa2DEEIjPCc0wcNrHoAhakLCKjTf9G+0rj2yYb+bwBvVPg4iAG9ggEMEsdQyUcaWUiu4o8sC4tRxyldlVddQna5l0HYesHr/X6EQ2yaR1ClLFqjQHjAd2bOtvICNCbbVLPjDfL81t9MyamMPLBU/nz4DWv//p/qqwoeT2BwlAo6hsxoWIp9Ffv+1b9muqdk/oxEi3dFgM6VnQxy/lj6sT1cNXUXCuJa6QOYLrvWntSUetTi3UfO77T4KZwCw9zHJ24Z5KRLBTj0A0lAu7vo8B4HZjHtnAPin+bn+/HB6Epk+Gk8CERdMfQx7qmnGLNJ3mERIiY5dgcMLys9a33iGC53OnngIJIVcLJ9cvUVN1wNjkmUZR7vzrpdV1UUA9Kji5fUh4TChNjwKzgU/ux1fPdFyVL7vMZhkwktObKPjYH/o33p/E1SvDXb9YrlEHMeNphb80UFillzSPzzvkxaAw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
